plugins {
    id 'net.fabricmc.fabric-loom-remap' version "${loom_version}"
    id 'maven-publish'
    id 'idea'
}

version = "${minecraft_version}-${mod_version}"
group = maven_group

base {
    archivesName = archives_base_name
}

sourceSets {
    main {
        java {
            exclude 'com/github/alexmodguy/retrodamageindicators/**'
        }
        resources {
            exclude 'retrodamageindicators.mixins.json'
            exclude 'META-INF/neoforge.mods.toml'
            exclude 'META-INF/mods.toml'
            exclude 'META-INF/accesstransformer.cfg'
        }
    }
}

loom {
    splitEnvironmentSourceSets()

    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
            sourceSet sourceSets.client
        }
    }
}

dependencies {
    minecraft "com.mojang:minecraft:${minecraft_version}"
    mappings loom.officialMojangMappings()
    modImplementation "net.fabricmc:fabric-loader:${loader_version}"
    modImplementation "net.fabricmc.fabric-api:fabric-api:${fabric_api_version}"
}

processResources {
    inputs.property 'version', project.version
    inputs.property 'mod_id', mod_id
    inputs.property 'mod_name', mod_name
    inputs.property 'mod_license', mod_license
    inputs.property 'mod_authors', mod_authors
    inputs.property 'mod_credits', mod_credits

    filesMatching('fabric.mod.json') {
        expand(
                'version': project.version,
                'mod_id': mod_id,
                'mod_name': mod_name,
                'mod_license': mod_license,
                'mod_authors': mod_authors,
                'mod_credits': mod_credits
        )
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    options.release = 21
}

java {
    withSourcesJar()
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}

publishing {
    publications {
        register('mavenJava', MavenPublication) {
            from components.java
        }
    }
    repositories {
        maven {
            url = "file://${project.projectDir}/repo"
        }
    }
}

idea {
    module {
        downloadSources = true
        downloadJavadoc = true
    }
}
