# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
org.gradle.jvmargs=-Xmx1G -Djava.net.preferIPv4Stack=true
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false

# Fabric — https://fabricmc.net/develop
minecraft_version=1.21.11
loader_version=0.18.3
loom_version=1.14-SNAPSHOT
fabric_api_version=0.141.3+1.21.11

## Mod Properties
mod_id=damageindicators
mod_name=Damage Indicators
mod_license=GNU
mod_version=1.21.11-1.0.0
maven_group=com.astryxion.damageindicators
archives_base_name=damageindicatorsfabric
mod_authors=Astryxion
mod_credits=Astryxion
