modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/AlexModGuy/RetroDamageIndicators/issues"

[[mods]]
modId="${mod_id}"
version="1.0.0"
displayName="Damage Indicators (Classic)"
displayURL=""
logoFile="assets/retrodamageindicators/textures/mod_logo.png"
authors="Astryxion"
credits="Astryxion"
description='''A mob health indicator on the in-game HUD that is reminiscent of modded days long gone...'''

[[dependencies.retrodamageindicators]]
modId="neoforge"
mandatory=false
versionRange="[20,)"
ordering="NONE"
side="CLIENT"
