org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false

parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17

minecraft_version=1.21.1
minecraft_version_range=[1.21.1]
neo_version=21.1.233
loader_version_range=[4,)

mod_id=damageindicators
mod_name=Damage Indicators (Expanded)
mod_license=GNU GENERAL PUBLIC LICENSE Version 3
mod_version=1.21.1-1.1.0
mod_group_id=com.astryxion.damageindicators
mod_authors=Astryxion
mod_description=A damage indicators mod with multiple visual styles. Switch between a modern Retro Damage Indicators look and the classic nostalgic Damage Indicators 1.12.2 HUD and popoffs.
