org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=1.16.5
forge_version=36.2.34
mapping_channel=official
mapping_version=1.16.5

mod_id=damageindicators
mod_name=Damage Indicators (Expanded)
mod_license=GNU GENERAL PUBLIC LICENSE Version 3
mod_version=1.16.5-1.1.0
mod_group_id=com.astryxion.damageindicators
mod_authors=Astryxion
mod_description=A damage indicators mod with multiple visual styles. Switch between a modern Retro Damage Indicators look and the classic nostalgic Damage Indicators 1.12.2 HUD and popoffs.
archives_base_name=damageindicatorsforge
