modLoader="javafml"
loaderVersion="[36,)"
license="GNU GENERAL PUBLIC LICENSE Version 3"
issueTrackerURL="https://github.com/astryxion/Damage-Indicators/issues"

[[mods]]
modId="damageindicators"
version="${mod_version}"
displayName="Damage Indicators (Expanded)"
displayURL="https://github.com/astryxion/Damage-Indicators"
authors="Astryxion"
credits="Astryxion, Alexthe668, Ron0, rich1051414"
description='''A damage indicators mod with multiple visual styles. Switch between a modern Retro Damage Indicators look and the classic nostalgic Damage Indicators 1.12.2 HUD and popoffs.'''

[[dependencies.damageindicators]]
modId="forge"
mandatory=true
versionRange="[36.2.34,)"
ordering="NONE"
side="CLIENT"

[[dependencies.damageindicators]]
modId="minecraft"
mandatory=true
versionRange="[1.16.5]"
ordering="NONE"
side="CLIENT"
